# Generated by Django 6.1.1 on 2026-09-27 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.TextField(
                max_length=1000,
                validators=[django.core.validators.MaxLengthValidator(1000)],
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(
                max_length=2000,
                validators=[django.core.validators.MaxLengthValidator(2000)],
            ),
        ),
    ]
