# Generated by Django 6.1.1 on 2026-09-27 09:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="total budget (USD)",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="INACTIVE",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "advertiser",
                    models.ForeignKey(
                        limit_choices_to={"role": "ADVERTISER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("advertiser", "name"),
                        name="ads_campaign_unique_name_per_advertiser",
                        violation_error_message="You already have a campaign with this name.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("budget__gt", 0)),
                        name="ads_campaign_budget_positive",
                        violation_error_message="Budget must be greater than zero.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("end_date__gte", models.F("start_date"))),
                        name="ads_campaign_end_after_start",
                        violation_error_message="End date can't be before the start date.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["ACTIVE", "INACTIVE"])),
                        name="ads_campaign_status_valid",
                    ),
                ],
            },
        ),
    ]
