# Generated by Django 6.1.1 on 2026-09-27 09:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_campaign"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=90)),
                (
                    "body",
                    models.TextField(
                        max_length=300,
                        validators=[django.core.validators.MaxLengthValidator(300)],
                        verbose_name="body text",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="ads/%Y/%m/")),
                (
                    "target_url",
                    models.URLField(
                        help_text="Where people go when they click the ad (http or https).",
                        max_length=500,
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"]
                            )
                        ],
                        verbose_name="target URL",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_units",
                        to="ads.campaign",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["campaign", "created_at"],
                        name="ads_adunit_campaign_time_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("headline", ""), _negated=True),
                        name="ads_adunit_headline_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("body", ""), _negated=True),
                        name="ads_adunit_body_not_empty",
                    ),
                ],
            },
        ),
    ]
