# Generated by Django 6.1.1 on 2026-09-27 10:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0003_adunit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["status", "start_date", "end_date"],
                name="ads_campaign_serving_idx",
            ),
        ),
    ]
